//
// Created by 33695 on 16/11/2023.
//

#ifndef PROJET_SNOOPY_CHARGEMENT_NIVEAUX_H
#define PROJET_SNOOPY_CHARGEMENT_NIVEAUX_H

int menu();
void option4_menu();

#endif //PROJET_SNOOPY_CHARGEMENT_NIVEAUX_H
